site_name: Terminal
site_url: https://johanneslatzel.github.io/terminal/
repo_url: https://github.com/johanneslatzel/terminal
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
  - Quick Start: quickstart.md
  - Architecture: architecture.md
  - Built-ins: builtins.md
  - Terminal: terminal/index.md
  - Commands:
    - Overview: commands/index.md
    - Classes: commands/classes.md
    - Definitions: commands/definitions.md
  - Arguments: arguments/index.md
  - Hooks: hooks/index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
